# Generated by Django 6.0.3 on 2026-03-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_video_id', models.CharField(blank=True, help_text='e.g., for https://youtube.com/watch?v=dQw4w9, the ID is dQw4w9', max_length=50)),
                ('article_link', models.URLField(blank=True, help_text='Use this if linking to a blog post instead of a video')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., BS Computer Science Thesis', max_length=200)),
                ('institution_or_publisher', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('description', models.TextField(help_text='Highlight research rigor, methodology, and findings.')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Full-Stack Web Development, Web Scraping', max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='FontAwesome icon class, e.g., fa-code, fa-database, fa-spider', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True, help_text='What problem were you solving?', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, help_text='How did you solve it?', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Brief overview for the homepage.'),
        ),
    ]
