# Generated by Django 6.0.3 on 2026-03-23 07:42

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_mediacontent_publication_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
            ],
        ),
        migrations.DeleteModel(
            name='MediaContent',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about_description_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='problem_statement',
        ),
        migrations.RemoveField(
            model_name='project',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_description_1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Brief overview for the homepage.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Main cover/thumbnail image', null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='me.project'),
        ),
    ]
