# Generated by Django 6.0.3 on 2026-04-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0003_projectimage_delete_mediacontent_delete_publication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Basic, Standard, Premium', max_length=50)),
                ('title', models.CharField(help_text='e.g. Landing Page, Full Web App', max_length=100)),
                ('price', models.CharField(help_text='e.g. $20, $100+', max_length=50)),
                ('description', models.TextField()),
                ('delivery_time', models.CharField(help_text='e.g. 2-5 days', max_length=50)),
                ('revisions', models.CharField(help_text='e.g. 2 Revisions, Unlimited', max_length=50)),
                ('features', models.TextField(help_text='Comma-separated list of features (e.g. Responsive Design, Source Code)')),
                ('is_best_seller', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Order to display on the page (1, 2, 3)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
