# Generated by Django 6.0.3 on 2026-04-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_faq_review_servicepackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackage',
            name='features',
            field=models.TextField(help_text='Comma-separated list (e.g. Responsive Design, Source Code)'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='order',
            field=models.IntegerField(default=0, help_text='Order to display (1, 2, 3)'),
        ),
    ]
