# Generated by Django 6.0.3 on 2026-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0005_alter_servicepackage_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('project_description', models.TextField(help_text='Details about the project')),
                ('reference_link', models.URLField(blank=True, help_text='Link to a reference website/UI', null=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='order_references/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
