# Generated by Django 6.0.3 on 2026-04-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0006_orderrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderRequest',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='delivery_time',
            field=models.CharField(help_text='e.g. 2 Days', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='features',
            field=models.TextField(help_text='Comma-separated list (e.g. Responsive Design, Clean Code, SEO)'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (1, 2, 3)'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='price',
            field=models.CharField(help_text='e.g. $20, $50, $100+', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='title',
            field=models.CharField(help_text='e.g. Landing Page, Website, Full Web App', max_length=100),
        ),
    ]
