# Generated by Django 6.0.3 on 2026-04-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0007_delete_orderrequest_delete_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, help_text="Client's location/country", max_length=200, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('reference_link', models.URLField(blank=True, help_text='Link to reference UI/Website', null=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='service_references/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
