# Generated by Django 6.0.3 on 2026-04-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0008_servicecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='category',
            field=models.CharField(choices=[('Full Stack Website Development', 'Full Stack Website Development'), ('Frontend Development', 'Frontend Development'), ('Backend Development', 'Backend Development'), ('Web Scraping', 'Web Scraping'), ('Other', 'Other')], default='Full Stack Website Development', max_length=100),
        ),
    ]
